// This file was generated by silverstripe/tx-translator from client/lang/src/en.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('en', {
    "MFAWebAuthnRegister.BACK": "Back",
    "MFAWebAuthnRegister.COMPLETEREGISTRATION": "Complete registration",
    "MFAWebAuthnRegister.DESCRIPTION": "Contact your administrator if you require a security key. ",
    "MFAWebAuthnRegister.FAILURE": "Something went wrong. Please re-insert your key and try again",
    "MFAWebAuthnRegister.HELP": "How to use security keys.",
    "MFAWebAuthnRegister.INSTRUCTION": "Insert security key and press {button}",
    "MFAWebAuthnRegister.REGISTER": "Register key",
    "MFAWebAuthnRegister.REGISTERING": "Registering",
    "MFAWebAuthnRegister.RETRY": "Retry",
    "MFAWebAuthnRegister.SUCCESS": "Key verified",
    "MFAWebAuthnRegister.WAITING": "Waiting",
    "MFAWebAuthnVerify.DESCRIPTION": "Use your security key to verify your identity.",
    "MFAWebAuthnVerify.FAILURE": "Something went wrong, please re-insert your key and try again",
    "MFAWebAuthnVerify.HELP": "How to use security keys.",
    "MFAWebAuthnVerify.INSTRUCTION": "Please insert your security key and {button}.",
    "MFAWebAuthnVerify.RETRY": "Try again",
    "MFAWebAuthnVerify.SUCCESS": "Logging in...",
    "MFAWebAuthnVerify.VERIFY": "activate it",
    "MFAWebAuthnVerify.WAITING": "Waiting..."
});
}