// This file was generated by silverstripe/cow from client/lang/src/nl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "MFAWebAuthnRegister.BACK": "Terug",
    "MFAWebAuthnRegister.COMPLETEREGISTRATION": "Rond registratie af",
    "MFAWebAuthnRegister.DESCRIPTION": "Neem contact op het beheerder indien u een beveiligings sleutel nodig heeft. ",
    "MFAWebAuthnRegister.FAILURE": "Something went wrong. Please re-insert your key and try again",
    "MFAWebAuthnRegister.HELP": "How to use security keys.",
    "MFAWebAuthnRegister.INSTRUCTION": "Insert security key and press {button}",
    "MFAWebAuthnRegister.REGISTER": "Register key",
    "MFAWebAuthnRegister.REGISTERING": "Registering",
    "MFAWebAuthnRegister.RETRY": "Opnieuw proberen",
    "MFAWebAuthnRegister.SUCCESS": "Key verified",
    "MFAWebAuthnRegister.WAITING": "Wachten",
    "MFAWebAuthnVerify.DESCRIPTION": "Use your security key to verify your identity.",
    "MFAWebAuthnVerify.FAILURE": "Something went wrong, please re-insert your key and try again",
    "MFAWebAuthnVerify.HELP": "How to use security keys.",
    "MFAWebAuthnVerify.INSTRUCTION": "Please insert your security key and {button}.",
    "MFAWebAuthnVerify.RETRY": "Try again",
    "MFAWebAuthnVerify.SUCCESS": "Logging in...",
    "MFAWebAuthnVerify.VERIFY": "activate it",
    "MFAWebAuthnVerify.WAITING": "Waiting..."
});
}