// This file was generated by silverstripe/tx-translator from client/lang/src/nl.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "MFAWebAuthnRegister.BACK": "Terug",
    "MFAWebAuthnRegister.COMPLETEREGISTRATION": "Rond registratie af",
    "MFAWebAuthnRegister.DESCRIPTION": "Neem contact op het beheerder indien u een beveiligings sleutel nodig heeft. ",
    "MFAWebAuthnRegister.FAILURE": "Er is iets misgegaan. Sluit de sleutel opnieuw aan en probeer opnieuw",
    "MFAWebAuthnRegister.HELP": "Over het gebruik van beveiligingssleutels",
    "MFAWebAuthnRegister.INSTRUCTION": "Voer je beveiligingssleutel in en {button} deze",
    "MFAWebAuthnRegister.REGISTER": "Sleutel aanmaken",
    "MFAWebAuthnRegister.REGISTERING": "Registreren",
    "MFAWebAuthnRegister.RETRY": "Opnieuw proberen",
    "MFAWebAuthnRegister.SUCCESS": "Sleutel verifieren",
    "MFAWebAuthnRegister.WAITING": "Wachten",
    "MFAWebAuthnVerify.DESCRIPTION": "Gebruik de beveiligingssleutel om verder te gaan.",
    "MFAWebAuthnVerify.FAILURE": "Er is iets misgegaan. Sluit de sleutel opnieuw aan en probeer opnieuw",
    "MFAWebAuthnVerify.HELP": "Over het gebruik van beveiligingssleutels",
    "MFAWebAuthnVerify.INSTRUCTION": "Voer sleutel in en {button}",
    "MFAWebAuthnVerify.RETRY": "Opnieuw proberen",
    "MFAWebAuthnVerify.SUCCESS": "Inloggen...",
    "MFAWebAuthnVerify.VERIFY": "activeer",
    "MFAWebAuthnVerify.WAITING": "Wachten...",
    "WebAuthnReducer.NOT_ON_HTTPS": "Dit kan alleen gebruikt worden met HTTPS.",
    "WebAuthnReducer.UNSUPPORTED_BROWSER": "Beveiligingssleutels worden niet ondersteund in deze browser."
});
}