// This file was generated by silverstripe/cow from client/lang/src/nl.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('nl', {
    "MFAWebAuthnRegister.BACK": "Terug",
    "MFAWebAuthnRegister.COMPLETEREGISTRATION": "Rond registratie af",
    "MFAWebAuthnRegister.DESCRIPTION": "Neem contact op het beheerder indien u een beveiligings sleutel nodig heeft. ",
    "MFAWebAuthnRegister.FAILURE": "Er is iets misgegaan. Sluit de sleutel opnieuw aan en probeer opnieuw",
    "MFAWebAuthnRegister.HELP": "Over het gebruik van beveiligingssleutels",
    "MFAWebAuthnRegister.INSTRUCTION": "Sleutel invoeren en druk op {button}",
    "MFAWebAuthnRegister.REGISTER": "Sleutel aanmaken",
    "MFAWebAuthnRegister.REGISTERING": "Registreren",
    "MFAWebAuthnRegister.RETRY": "Opnieuw proberen",
    "MFAWebAuthnRegister.SUCCESS": "Sleutel verifieren",
    "MFAWebAuthnRegister.WAITING": "Wachten",
    "MFAWebAuthnVerify.DESCRIPTION": "Gebruik de beveiligingssleutel om verder te gaan.",
    "MFAWebAuthnVerify.FAILURE": "Er is iets misgegaan. Sluit de sleutel opnieuw aan en probeer opnieuw",
    "MFAWebAuthnVerify.HELP": "Over het gebruik van beveiligingssleutels",
    "MFAWebAuthnVerify.INSTRUCTION": "Sleutel invoeren en druk op {button}",
    "MFAWebAuthnVerify.RETRY": "Opnieuw proberen",
    "MFAWebAuthnVerify.SUCCESS": "Inloggen...",
    "MFAWebAuthnVerify.VERIFY": "verrifieer",
    "MFAWebAuthnVerify.WAITING": "Wachten..."
});
}