// This file was generated by silverstripe/tx-translator from client/lang/src/sv.json.
// See https://github.com/silverstripe/silverstripe-tx-translator for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sv', {
    "MFAWebAuthnRegister.BACK": "Tillbaka",
    "MFAWebAuthnRegister.COMPLETEREGISTRATION": "Slutför registrering",
    "MFAWebAuthnRegister.DESCRIPTION": "Kontakta din administratör om säkerhetsnyckel krävs",
    "MFAWebAuthnRegister.FAILURE": "Något gick fel. Vänligen sätt i din nyckel igen och gör ett nytt försök",
    "MFAWebAuthnRegister.INSTRUCTION": "Sätt i säkerhetsnyckel och tryck på {button}",
    "WebAuthnReducer.NOT_ON_HTTPS": "Den här metoden kan enbart användas via HTTPS"
});
}