// This file was generated by silverstripe/cow from client/lang/src/sv.json.
// See https://github.com/tractorcow/cow for details
if (typeof(ss) === 'undefined' || typeof(ss.i18n) === 'undefined') {
  if (typeof(console) !== 'undefined') { // eslint-disable-line no-console
    console.error('Class ss.i18n not defined');  // eslint-disable-line no-console
  }
} else {
  ss.i18n.addDictionary('sv', {
    "MFAWebAuthnRegister.BACK": "Tillbaka",
    "MFAWebAuthnRegister.COMPLETEREGISTRATION": "Slutför registrering",
    "MFAWebAuthnRegister.DESCRIPTION": "Kontakta din administratör om säkerhetsnyckel krävs",
    "MFAWebAuthnRegister.FAILURE": "Något gick fel. Vänligen sätt i din nyckel igen och gör ett nytt försök",
    "MFAWebAuthnRegister.HELP": "How to use security keys.",
    "MFAWebAuthnRegister.INSTRUCTION": "Sätt i säkerhetsnyckel och tryck på {button}",
    "MFAWebAuthnRegister.REGISTER": "Register key",
    "MFAWebAuthnRegister.REGISTERING": "Registering",
    "MFAWebAuthnRegister.RETRY": "Retry",
    "MFAWebAuthnRegister.SUCCESS": "Key verified",
    "MFAWebAuthnRegister.WAITING": "Waiting",
    "MFAWebAuthnVerify.DESCRIPTION": "Use your security key to verify your identity.",
    "MFAWebAuthnVerify.FAILURE": "Something went wrong, please re-insert your key and try again",
    "MFAWebAuthnVerify.HELP": "How to use security keys.",
    "MFAWebAuthnVerify.INSTRUCTION": "Please insert your security key and {button}.",
    "MFAWebAuthnVerify.RETRY": "Try again",
    "MFAWebAuthnVerify.SUCCESS": "Logging in...",
    "MFAWebAuthnVerify.VERIFY": "activate it",
    "MFAWebAuthnVerify.WAITING": "Waiting..."
});
}